# Generated by Django 4.1.7 on 2023-04-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprojectstatistics',
            name='is_created_project',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, verbose_name='Проект создан этим автором?'),
        ),
    ]
