# Generated by Django 4.1.7 on 2023-04-03 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='star',
            name='liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='star',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='links.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='editor',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects_edit', to=settings.AUTH_USER_MODEL, verbose_name='Редакторы'),
        ),
        migrations.AddField(
            model_name='project',
            name='main_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='создатель'),
        ),
        migrations.AddField(
            model_name='project',
            name='theme',
            field=models.ManyToManyField(blank=True, help_text='Выберите тематику проекта', null=True, related_name='projects', to='links.theme', verbose_name='Тематика'),
        ),
        migrations.AddField(
            model_name='link',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='links.head'),
        ),
        migrations.AddField(
            model_name='head',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heads', to='links.project'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='links.link'),
        ),
        migrations.CreateModel(
            name='ProxyProjectOrderedDesc',
            fields=[
            ],
            options={
                'ordering': ('created',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('links.project',),
        ),
        migrations.CreateModel(
            name='ProxyProjectOrderedStars',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('links.project',),
        ),
    ]
