# Generated by Django 4.1.7 on 2023-04-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
