# Generated by Django 4.1.7 on 2023-04-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_project_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='saved_users',
        ),
    ]
