# Generated by Django 3.0 on 2023-03-25 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0002_auto_20230325_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='editor',
            field=models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='оедакторы'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='создатель'),
        ),
        migrations.AlterField(
            model_name='project',
            name='theme',
            field=models.ManyToManyField(blank=True, related_name='projects', to='links.Theme', verbose_name='направления'),
        ),
    ]
