# Generated by Django 4.1.7 on 2023-05-02 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0003_rename_user_project_saved_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Star',
        ),
    ]
