# Generated by Django 4.1.7 on 2023-04-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_alter_head_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='head',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер раздела'),
        ),
    ]
