# Generated by Django 3.0 on 2023-03-26 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0004_project_is_group_project_project_is_private_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ('name',), 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AlterField(
            model_name='head',
            name='description',
            field=models.TextField(blank=True, help_text='Добавьте описание', null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='head',
            name='title',
            field=models.CharField(help_text='Введите название', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.TextField(blank=True, help_text='Добавьте описание', null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(help_text='Введите название', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Добавьте описание', null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='editor',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects_edit', to=settings.AUTH_USER_MODEL, verbose_name='Редакторы'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_group_project',
            field=models.BooleanField(choices=[(True, 'Группа'), (False, 'Только я')], default=False, verbose_name='Кто может работать с проектом'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_private',
            field=models.BooleanField(choices=[(True, 'Private'), (False, 'Public')], default=False, help_text='Укажите, кому будет доступен этот проект: public - доступен только создателю и редакторам; private - доступен для всех пользователей', verbose_name='Тип проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='theme',
            field=models.ManyToManyField(blank=True, help_text='Выберите тематику проекта', null=True, related_name='projects', to='links.Theme', verbose_name='Тематика'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Введите название', max_length=100, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='links.Project')),
            ],
            options={
                'verbose_name': 'Звезда',
                'verbose_name_plural': 'Звезды',
            },
        ),
    ]
