# Generated by Django 4.1.7 on 2023-05-09 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0004_project_liked_users_delete_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='editor',
            field=models.ManyToManyField(blank=True, related_name='projects_edit', to=settings.AUTH_USER_MODEL, verbose_name='Редакторы'),
        ),
        migrations.AlterField(
            model_name='project',
            name='theme',
            field=models.ManyToManyField(blank=True, help_text='Выберите тематику проекта. Для выбора нескольких значений зажмите Alt.', related_name='projects', to='links.theme', verbose_name='Тематика'),
        ),
    ]
