# Generated by Django 4.1.7 on 2023-04-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_alter_theme_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxyproject',
            fields=[
            ],
            options={
                'ordering': ('created',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('links.project',),
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created',), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
