# Generated by Django 4.1.7 on 2023-05-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_alter_project_editor_alter_project_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprojectstatistics',
            name='last_visit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего просмотра проекта'),
        ),
    ]
