# Generated by Django 4.1.7 on 2023-04-03 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_alter_head_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='head',
            options={'verbose_name': 'раздел', 'verbose_name_plural': 'разделы'},
        ),
        migrations.AlterUniqueTogether(
            name='head',
            unique_together={('project', 'number')},
        ),
    ]
