# Generated by Django 4.1.7 on 2023-04-01 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_proxyproject_alter_project_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyProjectOrderedDesc',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='links.project')),
            ],
            options={
                'ordering': ('created',),
            },
            bases=('links.project',),
        ),
        migrations.DeleteModel(
            name='Proxyproject',
        ),
        migrations.CreateModel(
            name='ProxyProjectOrderedStars',
            fields=[
            ],
            options={
                'ordering': ('created',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('links.project',),
        ),
    ]
