# Generated by Django 4.1.7 on 2023-04-01 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_proxyprojectordereddesc_delete_proxyproject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxyprojectorderedstars',
            options={'ordering': ('-stars',)},
        ),
        migrations.DeleteModel(
            name='ProxyProjectOrderedDesc',
        ),
        migrations.CreateModel(
            name='ProxyProjectOrderedDesc',
            fields=[
            ],
            options={
                'ordering': ('created',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('links.project',),
        ),
    ]
