# Generated by Django 4.1.7 on 2023-04-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_alter_proxyprojectorderedstars_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxyprojectorderedstars',
            options={},
        ),
    ]
