# Generated by Django 4.1.7 on 2023-04-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_alter_link_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='theme',
            field=models.ManyToManyField(blank=True, help_text='Выберите тематику проекта. Для выбора нескольких значений зажмите Alt.', null=True, related_name='projects', to='links.theme', verbose_name='Тематика'),
        ),
    ]
