# Generated by Django 4.1.7 on 2023-04-02 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0008_alter_proxyprojectorderedstars_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, upload_to='profile_image', verbose_name='Изображение профиля')),
                ('about_info', models.TextField(blank=True, help_text='Укажите личную информацию о себе', verbose_name='О себе')),
                ('first_name', models.CharField(blank=True, help_text='Укажите свое имя', max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Укажите свою фамилию', max_length=40, verbose_name='Фамилия')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
