# Generated by Django 4.1.7 on 2023-04-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0008_alter_project_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='Files', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка'),
        ),
    ]
