# Generated by Django 4.1.7 on 2023-04-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0009_link_document_alter_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='document',
            field=models.FileField(blank=True, help_text='Выберите нужный документ', null=True, upload_to='Files', verbose_name='Документ'),
        ),
    ]
